---
- name: Provision VM
  hosts: all
  become: yes
  become_method: sudo
  remote_user: ubuntu
  tasks:
      - import_tasks: system_administration/pam_pwquality.yml
      - import_tasks: system_administration/user_and_group.yml
      - import_tasks: ssh_configuration/authorized_keys.yml
      - import_tasks: ssh_configuration/two_factor.yml
      - import_tasks: web_app/web_application.yml
      - import_tasks: web_app/sudoers.yml
      - import_tasks: firewall/firewall.yml
  handlers:
      - import_tasks: handlers/restart_ssh.yml
